export default {
  SET_SELECTED_EVENT_ID: 'SET_SELECTED_EVENT_ID',
  RESET_FAVORING_AND_UPDATE_FAILURE: 'RESET_FAVORING_AND_UPDATE_FAILURE',
  RESET_RATING_AND_UPDATE_FAILURE: 'RESET_RATING_AND_UPDATE_FAILURE',
};
