export default {
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  SET_LANGUAGE: 'SET_LANGUAGE',
  UPDATE_CURRENT_DATE: 'UPDATE_CURRENT_DATE',
  ONBOARDING_HAS_BEEN_SEEN: 'ONBOARDING_HAS_BEEN_SEEN',
  STORE_SIGN_UP_DATA: 'STORE_SIGN_UP_DATA',
  RESET_SIGN_IN_FAILURE: 'RESET_SIGN_IN_FAILURE',
  RESET_SIGN_UP_FAILURE: 'RESET_SIGN_UP_FAILURE',
  HAS_SKIPPED_TAG_SELECTION: 'HAS_SKIPPED_TAG_SELECTION',
  SAVE_USER_TAGS: 'SAVE_USER_TAGS',
  LOG_USER_OUT: 'LOG_USER_OUT',
  SET_CURRENT_COMPONENT_ID: 'SET_CURRENT_COMPONENT_ID',
};
