export default {
  ABOUT_SAUDI: 'AboutSaudi',
  SUPPORT: 'Support',
  ARTICLE_DETAIL: 'ArticleDetail',
  ONBOARDING: 'Onboarding',
  TODAY: 'Today',
  CATEGORIES_RESULT: 'CategoriesResults',
  FAVORITES: 'Favorites',

  SEARCH_MAP: 'SearchMap',
  SEARCH: 'Search',

  ENABLE_LOCATION: 'EnableLocation',
  TURN_NOTIFICATIONS: 'TurnNotifications',
  PERSONALIZED_LIST: 'PersonalizedList',
  EXPLORE_RIYADH: 'ExploreRiyadh',
  SETTINGS: 'Settings',
  EDIT_PROFILE: 'EditProfile',
  FESTIVITIES: 'Festivities',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  PICK_UP_PASSWORD: 'PickUpPassword',
  MAP_FESTIVITIES: 'MapFestivities',
  PRIVACY_POLICY: 'PrivacyPolicy',
  PICK_INTERESTS: 'PickInterests',
  FORGOT_PASSWORD: 'ForgotPassword',
};
